// Auto-generated by train.py. Do not edit by hand.
#ifndef GESTURE_LABELS_H_
#define GESTURE_LABELS_H_

const int kNumGestureClasses = 4;
const char* kGestureLabels[] = {"idle", "wave", "circle", "punch"};

#endif  // GESTURE_LABELS_H_
